### ISSUE TITLE
Chapters not available in internal reader.

### ISSUE THREAD

**Issue by edl2** [dstark5/Openlib#4] opened 2023-08-13 04:38 UTC
Add this book
![Screenshot_20230813_003554](https://github.com/dstark5/Openlib/assets/95947898/559b9536-ca5f-4252-8017-99e4d24a17b7)

Internal reader parses the epub wrong. None of the chapter contents is available to be read. However opening the epub file with an external reader like librera you can read it just fine.

**Comment by dstark5** [comment] 2023-08-13 11:56
I have checked the issue and found the same bug you mentioned . The bug is caused by 'epub_view' package and the bug will be fixed in the next update .Until that download and read the epub  of size 4.6Mb in the result which is same book as the issue only occurs with epub of size 0.7Mb.

**Comment by dstark5** [comment] 2023-09-04 06:53
Hi, The issue have been fixed in the latest release 1.0.1 update it and if you satisfied close the issue

**Comment by dstark5** [comment] 2023-11-04 05:25
The new version 1.0.3 fixed the issues use it with a VPN

**Closed by dstark5** 2023-11-04 05:25 UTC
Labels: bug, good first issue
