### ISSUE TITLE
failed to download 

### ISSUE THREAD

**Issue by Fahad-Khan1** [dstark5/Openlib#68] opened 2024-02-15 20:29 UTC
the error is everywhere in the app can't download a single book

**Comment by inson1** [comment] 2024-02-16 06:56
duplicate of https://github.com/dstark5/Openlib/issues/65

So please close it this issue :)

**Comment by dstark5** [comment] 2024-02-25 13:22
This error has been fixed in the latest version of app

**Closed** 2024-03-10 13:28 UTC
