### ISSUE TITLE
Grey overlay on failed download after checking mirrors

### ISSUE THREAD

**Issue by ScottWilliamAnderson** [dstark5/Openlib#58] opened 2024-01-14 12:19 UTC
When attempting to download any book, (this is with a VPN on as without it the download fails instantly), the app checks for mirrors for ~5 seconds, then the looping circle animation turns into a checkmark ✅ (but the 0b/0b and the loading bar do not change).
Then the screen turns grey with an overlay and the app is unresponsive. After restarting the app, the book is not in the library.

I'm on Android 13, running Openlib 1.0.4

Is there a way to share the logs? Happy to do so if available.

**Comment by ScottWilliamAnderson** [comment] 2024-01-14 12:19
![Screenshot_20240114-121419.jpg](https://github.com/dstark5/Openlib/assets/47524721/6f02a3b9-3666-4d20-a2a8-429752dbc740)

![Screenshot_20240114-121413.jpg](https://github.com/dstark5/Openlib/assets/47524721/fe23edc3-e687-4522-9fad-c6748f4f2b19)

**Comment by inson1** [comment] 2024-01-14 12:39
it happened to me to 
like 3 times

@ScottWilliamAnderson What vpn did you used?

**Comment by ScottWilliamAnderson** [comment] 2024-01-14 14:57
> it happened to me too
> like 3 times
> 
> @ScottWilliamAnderson What vpn did you use?
> 

ProtonVPN, you?

**Comment by inson1** [comment] 2024-01-14 17:14
It only happened to me with Tor (with orbot), it never yet happened to me with proton vpn (yes I'm using it too)

**Comment by dstark5** [comment] 2024-01-16 05:46
does it occurs on every book or only ones

**Comment by ScottWilliamAnderson** [comment] 2024-01-16 08:50
> does it occurs on every book or only ones

Not all books. It looks like it happens most frequently with .cbr files? I haven't been able to test out enough books to pin it down. Sadly opening .cbr or .pdf fails (with or without external opening enabled). And sadly I can't access the files directly in the file explorer so I haven't been able to use Openlib as of yet

**Comment by DesolateIntention** [comment] 2024-01-18 16:28
Happened to me too. No VPN used.

**Comment by dstark5** [comment] 2024-01-19 07:33
> > does it occurs on every book or only ones
> 
> Not all books. It looks like it happens most frequently with .cbr files? I haven't been able to test out enough books to pin it down. Sadly opening .cbr or .pdf fails (with or without external opening enabled). And sadly I can't access the files directly in the file explorer so I haven't been able to use Openlib as of yet

will fix that error soon and will also add direct folder support

**Comment by dstark5** [comment] 2024-01-19 07:35
> Happened to me too. No VPN used.

would you provide me steps to reproduce the error or when the error occurs

**Comment by DesolateIntention** [comment] 2024-01-26 20:03
Search for "Heinkel: an aircraft album".
Click on the book with the same name. 
Click "Add To My Library".
Screen will turn gray.

**Comment by inson1** [comment] 2024-01-26 21:07
I cant reproduce it with that book

**Comment by DesolateIntention** [comment] 2024-01-26 21:44
> I cant reproduce it with that book

I remember when downloading books on that website the links sometimes didn't work, but clicking on them a few times usually fixed it. Could this be why it sometimes works and sometimes doesn't?

**Comment by inson1** [comment] 2024-01-26 22:12
yea I think so too

**Comment by dstark5** [comment] 2024-01-28 07:29
> ill fix that error soon and will also add direct folder support

Have successfully reproduced the error will fix it soon

**Comment by inson1** [comment] 2024-02-06 10:03
its in said is fixed in latest release notes

**Comment by inson1** [comment] 2024-02-15 12:08
btw its not fixed yet
the bug is still there

**Comment by sma33in** [comment] 2024-07-23 21:07
Hi; I also have encountered this issue, was never able to download a book. I have NextDNS set up, tried to disable it, use a VPN service. nothing worked.

**Comment by dstark5** [comment] 2024-08-31 11:21
Hi Everyone,
This issue is fixed in latest 1.0.7 build.
Thank you

**Closed** 2024-08-31 11:20 UTC
