### ISSUE TITLE
No mirror available 

### ISSUE THREAD

**Issue by abhay7430** [dstark5/Openlib#66] opened 2024-02-15 10:12 UTC
![Screenshot_20240215-153959](https://github.com/dstark5/Openlib/assets/123221572/f1255645-16d5-4aa1-9655-2feae706eaa5)

Whenever I touch the icon add to library their always comes a pop up message no mirror available please is solve this issue.🙏

**Comment by inson1** [comment] 2024-02-15 11:24
that was added in commit "Fixed gray screen error"

Cant we just not show it or filtering would be to slow?

**Comment by inson1** [comment] 2024-02-15 11:58
I have same problem

**Comment by dstark5** [comment] 2024-02-15 12:17
Hello guys 👋,

The issue is caused because of change in Anna's Archive website. Will fix the issue and release an update ASAP.

Thank you

**Comment by dstark5** [comment] 2024-02-15 12:24
I checked for the cause of grey screen error and fixed it in the previous release but I don't know what's causing it again, will figure out and fix it ASAP

**Comment by inson1** [comment] 2024-02-15 12:26
thank you

**Comment by inson1** [comment] 2024-02-18 13:42
@abhay7430 Why did you close it?

**Comment by abhay7430** [comment] 2024-02-19 01:11
> @abhay7430 Why did you close it?

I was just reading comments ,it happend unknowingly.

**Comment by dstark5** [comment] 2024-02-25 13:22
This error has been fixed in the latest version of app

**Comment by abhay7430** [comment] 2024-02-25 14:34
> This error has been fixed in the latest version of app

Thank you very much developer brother

**Closed** 2024-02-25 14:34 UTC

**Comment by genijuf** [comment] 2024-05-23 15:51
hello the issuse is still here on my graphene os it still says when trying to get any app  no working mirrors available i tried uninstalling the app and then installing it back a few times tried updating it through obtainium but nothing worked any idea how to fix it?
