### ISSUE TITLE
Exception: Incorrect EPUB manifest

### ISSUE THREAD

**Issue by 3LD** [dstark5/Openlib#19] opened 2023-08-24 16:45 UTC
Same error on multiple books. EPUB opens in caliber & playbooks.

![Screenshot_20230824_104030](https://github.com/dstark5/Openlib/assets/18621502/0d59c823-ce3e-4560-8062-7a70a34b0292)

**Comment by dstark5** [comment] 2023-08-25 14:14
The error is caused by epub view package. I have got a lot of issue on GitHub regarding the Epub viewer package will change the reader to a better one in the next update

**Comment by dstark5** [comment] 2023-09-04 06:49
Hi, The issue have been fixed in the latest release 1.0.1 update it and if you satisfied close the issue

**Closed** 2023-11-04 05:26 UTC
